### ISSUE TITLE
[Завершено] Отказ от веток

### ISSUE THREAD

**Issue by LeonusDH** [gravitlauncher-cheat/best-cheats#10]
Предлагаю, послать ветки лесом.
Почему? Потому, что ветки, придуманы не для того, чтобы хранить в них основной контент. Ветки, нужны, для структурирования, обновлений кода, чтобы, при смене версий, или при наличии нестабильных версий кода, уже рабочий код, можно было отослать, в основную ветку. Лицо репозитория, основная ветка!

И если вы живёте фразой: "Критикуешь, предлагай", то вот вам прекраснейшая мысль.
Переносим всё в папки! Нормально, структурируем папки и вот вам, нормальный вид репозитория.

**Comment by dima-dencep** [comment]
Полностью согласен, макар тоже согласен

**Comment by LeonusDH** [comment]
@dimadencep Когда успел спросить у Макара?

**Comment by dima-dencep** [comment]
А обезьян спрашивать не нужно

**Comment by LeonusDH** [comment]
Справедливо...

**Comment by dima-dencep** [comment]
щас я ему напишу

**Comment by dima-dencep** [comment]
ждем

**Comment by iocmet** [comment]
ок сносите

**Comment by LeonusDH** [comment]
В 1.12.2, dll под какую разрядность?

**Comment by LeonusDH** [comment]
jar там-же, мод или инжект?

**Comment by dima-dencep** [comment]
> В 1.12.2, dll под какую разрядность?

64x вроде

> jar там-же, мод или инжект?

jar это моды только

**Comment by dima-dencep** [comment]
@makarhuyaker ты их загружал
расскажи

**Comment by iocmet** [comment]
> В 1.12.2, dll под какую разрядность?

x64

**Comment by iocmet** [comment]
титанка не воркает я проверял

**Comment by iocmet** [comment]
игра крашится

**Comment by iocmet** [comment]
а ее нету в репе

**Comment by dima-dencep** [comment]
> титанка не воркает я проверял

она потому что под 1.6.4

**Comment by iocmet** [comment]
нет есть порт

**Comment by iocmet** [comment]
под 1,7,10 и 1,12,2

**Comment by iocmet** [comment]
но он кривой

**Comment by dima-dencep** [comment]
там под 1.6.4 лежала ток

**Comment by iocmet** [comment]
а

**Comment by iocmet** [comment]
у меня под 1,7,10 порт есть

**Comment by iocmet** [comment]
он крашит

**Comment by iocmet** [comment]
https://yadi.sk/d/pyLbPReZ3PPyhq

**Comment by dima-dencep** [comment]
у меня где то был

**Comment by dima-dencep** [comment]
рабочий, щас кину

**Comment by iocmet** [comment]
https://pvpru.com/b/t/titaniumdll-1-7-10.646848/

**Comment by iocmet** [comment]
а это другой

**Comment by dima-dencep** [comment]
ладно

**Comment by LeonusDH** [comment]
@makarhuyaker xray в 1.12.2 мод или инжект?

**Comment by iocmet** [comment]
какой иксрей

**Comment by iocmet** [comment]
тот который джар это мод

**Comment by LeonusDH** [comment]
@makarhuyaker Там только 1 xray

**Comment by iocmet** [comment]
а стоп а где zip

**Comment by iocmet** [comment]
[X-Ray (перекиньте папку de в minecraft.jar).zip](https://github.com/gravitlauncher-cheat/best-cheats/files/7286259/X-Ray.de.minecraft.jar.zip)

**Comment by iocmet** [comment]
вот для 1,7,10

**Comment by LeonusDH** [comment]
Так а мод, или инжект???

**Comment by iocmet** [comment]
блять который есть это мод

**Comment by LeonusDH** [comment]
@makarhuyaker в 1.7.10 уже же есть zip

**Comment by iocmet** [comment]
чего

**Comment by iocmet** [comment]
а

**Comment by iocmet** [comment]
ок

**Comment by LeonusDH** [comment]
Под 1.7.10 инжект значит...

**Comment by iocmet** [comment]
НЕТ

**Comment by iocmet** [comment]
ЭТО НЕ ИНЖЕКТ БЛЯ ТАМ В НАЗВАНИИ НАПИСАНО ЗИПНИКА

**Comment by LeonusDH** [comment]
Закинуть в minecraft.jar -_-

**Comment by LeonusDH** [comment]
Копец, ты агрессивный...

**Comment by iocmet** [comment]
> Закинуть в minecraft.jar -_-

и

**Comment by LeonusDH** [comment]
Ну так это тоже инжект -_-

**Comment by iocmet** [comment]
а ок

**Comment by iocmet** [comment]
я даун

**Comment by LeonusDH** [comment]
Перенёс

**Comment by iocmet** [comment]
ок
